[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jsonplaceholder-tests"
version = "0.1.0"
description = "API tests for JSONPlaceholder"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests",
    "pytest",
]

[tool.setuptools.packages.find]
include = ["src*"]  # найдет все пакеты в src/





